# Generated by Django 6.0.6 on 2026-07-11 15:12

import django.db.models.deletion
from django.conf import settings
from django.core.cache import cache
from django.db import migrations, models


PUBLIC_ROOT_CONFIG = {
    "public_root": True,
    "public_root_split_enabled": True,
    "public_root_url": "/",
    "public_root_title": "Switch Libya",
    "public_root_meta_description": "Smart locks, access control, installation and after-sale services from Switch Libya.",
    "show_titlebar_on_public": False,
    "show_sidebar_on_public": False,
}


def apply_public_staff_defaults(apps, schema_editor):
    SystemSettings = apps.get_model("dlux", "SystemSettings")
    for settings_obj in SystemSettings.objects.all():
        public_root_config = settings_obj.public_root_config
        if not isinstance(public_root_config, dict):
            public_root_config = {}
        public_root_config = {**public_root_config, **PUBLIC_ROOT_CONFIG}
        settings_obj.home_url = "/staff/workspace/"
        settings_obj.public_root_config = public_root_config
        settings_obj.save(update_fields=["home_url", "public_root_config"])
    cache.delete("SystemSettings")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_productvariant_purchaseinvoiceline_variant_and_more'),
        ('dlux', '0009_public_registration_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicCatalogListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('public_title', models.CharField(blank=True, max_length=220)),
                ('public_summary', models.CharField(blank=True, max_length=280)),
                ('public_body', models.TextField(blank=True)),
                ('image_override', models.ImageField(blank=True, upload_to='public_catalog/listings/')),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('show_price', models.BooleanField(default=True)),
                ('show_availability', models.BooleanField(default=True)),
                ('show_when_unavailable', models.BooleanField(default=True)),
                ('installation_notes', models.TextField(blank=True)),
                ('warranty_notes', models.TextField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=220)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='public_listings', to='catalog.product')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dlux.scope', verbose_name='Scope')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='public_listings', to='catalog.service')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Public Catalog Listing',
                'verbose_name_plural': 'Public Catalog Listings',
                'ordering': ['sort_order', 'public_title', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('service__isnull', True)), models.Q(('product__isnull', True), ('service__isnull', False)), _connector='OR'), name='public_listing_one_source'), models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('product',), name='uniq_public_listing_product'), models.UniqueConstraint(condition=models.Q(('service__isnull', False)), fields=('service',), name='uniq_public_listing_service')],
            },
        ),
        migrations.CreateModel(
            name='PublicContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('subject', models.CharField(blank=True, max_length=180)),
                ('message', models.TextField()),
                ('source_path', models.CharField(blank=True, max_length=300)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('email_status', models.CharField(choices=[('received', 'Received'), ('sent', 'Email sent'), ('failed', 'Email failed'), ('skipped', 'Skipped')], default='received', max_length=20)),
                ('email_recipient', models.EmailField(blank=True, max_length=254)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dlux.scope', verbose_name='Scope')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Public Contact Message',
                'verbose_name_plural': 'Public Contact Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='pub_contact_created_idx'), models.Index(fields=['email_status', 'created_at'], name='pub_contact_status_idx')],
            },
        ),
        migrations.RunPython(apply_public_staff_defaults, migrations.RunPython.noop),
    ]
