# Generated by Django 6.0.6 on 2026-07-05 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashdeposit',
            options={'ordering': ['-deposited_at', '-created_at'], 'permissions': [('confirm_cashdeposit', 'Can confirm or reject cash deposits'), ('view_all_cashdeposit', 'Can view all cash deposits (not just own)')], 'verbose_name': 'Cash Deposit', 'verbose_name_plural': 'Cash Deposits'},
        ),
    ]
