# Generated by Django 6.0.6 on 2026-07-10 13:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlux', '0003_dlux_update_runtime'),
        ('finance', '0002_alter_cashdeposit_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dlux.scope', verbose_name='Scope')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('amount_lyd', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount (LYD)')),
                ('expense_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Expense Date')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20, verbose_name='Method')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='Reference')),
                ('attachment', models.FileField(blank=True, upload_to='finance/expenses/', verbose_name='Receipt / Attachment')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('void', 'Void')], db_index=True, default='posted', max_length=12, verbose_name='Status')),
                ('posted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Posted At')),
                ('voided_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Voided At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Paid By')),
                ('posted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Posted By')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dlux.scope', verbose_name='Scope')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('voided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Voided By')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-expense_date', '-created_at'],
                'permissions': [('post_expense', 'Can post or void expenses'), ('view_all_expense', 'Can view all expenses (not just own)')],
            },
        ),
        migrations.CreateModel(
            name='StaffAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dlux.scope', verbose_name='Scope')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='finance_staff_account', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Staff Account',
                'verbose_name_plural': 'Staff Accounts',
                'ordering': ['user__username'],
                'permissions': [('view_all_staffaccount', 'Can view all staff accounts')],
            },
        ),
        migrations.CreateModel(
            name='StaffLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('entry_type', models.CharField(choices=[('service_earned', 'Service / commission earned'), ('reimbursement', 'Reimbursement due'), ('advance', 'Advance given'), ('loan', 'Loan given'), ('cash_checkout', 'Cash checked out'), ('item_checkout', 'Item checked out'), ('pay_staff', 'Payment to staff'), ('receive_from_staff', 'Payment from staff'), ('adjustment', 'Manual adjustment')], max_length=32, verbose_name='Type')),
                ('amount_lyd', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount (LYD)')),
                ('signed_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='Signed Amount')),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('status', models.CharField(choices=[('pending_user', 'Pending user confirmation'), ('posted', 'Posted'), ('disputed', 'Disputed'), ('void', 'Void')], db_index=True, default='pending_user', max_length=20, verbose_name='Status')),
                ('reference', models.CharField(blank=True, max_length=140, verbose_name='Reference')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('requires_user_confirmation', models.BooleanField(default=True, verbose_name='Require User Confirmation')),
                ('confirmed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Confirmed At')),
                ('posted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Posted At')),
                ('disputed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Disputed At')),
                ('notified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Notified At')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.staffaccount', verbose_name='Staff Account')),
                ('confirmed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_staff_entries', to=settings.AUTH_USER_MODEL, verbose_name='Confirmed By')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('disputed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputed_staff_entries', to=settings.AUTH_USER_MODEL, verbose_name='Disputed By')),
                ('posted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_staff_entries', to=settings.AUTH_USER_MODEL, verbose_name='Posted By')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dlux.scope', verbose_name='Scope')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Staff Ledger Entry',
                'verbose_name_plural': 'Staff Ledger Entries',
                'ordering': ['-entry_date', '-created_at'],
                'permissions': [('resolve_staffledgerentry', 'Can post, void, or resolve staff ledger entries'), ('view_all_staffledgerentry', 'Can view all staff ledger entries')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_lyd__gt', 0)), name='finance_staffentry_amount_positive')],
            },
        ),
    ]
