# Generated by Django 6.0.6 on 2026-07-04 12:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Profit added on top of the import cost. Changing it recalculates the USD selling price.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Markup %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_lyd_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to sell at the live rate; enter a value to fix the LYD price for this item.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Manual LYD Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Auto-filled from cost + markup; edit it directly and the markup follows.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Selling Price (USD)'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='A positive amount for Stock In / Stock Out; a signed (+/-) amount for an Adjustment.', max_digits=12, verbose_name='Quantity'),
        ),
    ]
