# Generated by Django 6.0.6 on 2026-07-08 00:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_markup_percent_and_more'),
        ('dlux', '0003_dlux_update_runtime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='catalog/products/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='catalog/services/', verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Count No.')),
                ('count_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Count Date')),
                ('status', models.CharField(choices=[('open', 'Open'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=12, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('applied_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Applied At')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dlux.scope', verbose_name='Scope')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Stock Take',
                'verbose_name_plural': 'Stock Takes',
                'ordering': ['-created_at'],
                'permissions': [('apply_stocktake', 'Can apply a stock take (post adjustments)'), ('view_inventory_valuation', 'Can view the inventory valuation report')],
            },
        ),
        migrations.CreateModel(
            name='StockTakeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_qty', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='System Qty')),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Counted Qty')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_take_lines', to='catalog.product', verbose_name='Product')),
                ('stock_take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='catalog.stocktake')),
            ],
            options={
                'verbose_name': 'Stock Take Line',
                'verbose_name_plural': 'Stock Take Lines',
                'ordering': ['product__name'],
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('stock_take', 'product'), name='uniq_stocktake_product')],
            },
        ),
    ]
