# Generated by Django 6.0.6 on 2026-07-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_purchaseinvoice_stockmovement_purchase_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('gray', 'Gray'), ('white', 'White'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('beige', 'Beige'), ('navy', 'Navy'), ('gold', 'Gold'), ('teal', 'Teal')], max_length=16, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Size / Spec'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('gray', 'Gray'), ('white', 'White'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('beige', 'Beige'), ('navy', 'Navy'), ('gold', 'Gold'), ('teal', 'Teal')], max_length=16, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='size',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Size / Spec'),
        ),
    ]
