# Generated by Django 6.0.6 on 2026-07-11 07:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def _norm(value):
    return (value or "").strip()


def backfill_product_variants(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    ProductVariant = apps.get_model("catalog", "ProductVariant")
    PurchaseInvoiceLine = apps.get_model("catalog", "PurchaseInvoiceLine")

    grouped = {}
    for line in PurchaseInvoiceLine.objects.all().only("id", "product_id", "color", "size", "quantity"):
        key = (line.product_id, _norm(line.color), _norm(line.size))
        grouped.setdefault(key, Decimal("0.00"))
        grouped[key] += line.quantity or Decimal("0.00")

    product_variant_ids = {}
    for (product_id, color, size), qty in grouped.items():
        variant, _created = ProductVariant.objects.get_or_create(
            product_id=product_id,
            color=color,
            size=size,
            defaults={"stock_qty": Decimal("0.00")},
        )
        variant.stock_qty = qty
        variant.save(update_fields=["stock_qty"])
        product_variant_ids[(product_id, color, size)] = variant.pk

    for product in Product.objects.all().only("id", "color", "size", "stock_qty"):
        product_keys = [key for key in product_variant_ids if key[0] == product.pk]
        if not product_keys and (product.color or product.size or product.stock_qty):
            color = _norm(product.color)
            size = _norm(product.size)
            variant, _created = ProductVariant.objects.get_or_create(
                product_id=product.pk,
                color=color,
                size=size,
                defaults={"stock_qty": Decimal("0.00")},
            )
            variant.stock_qty = product.stock_qty or Decimal("0.00")
            variant.save(update_fields=["stock_qty"])
            product_variant_ids[(product.pk, color, size)] = variant.pk
            product_keys = [(product.pk, color, size)]

        remaining = product.stock_qty or Decimal("0.00")
        for key in sorted(product_keys):
            variant = ProductVariant.objects.get(pk=product_variant_ids[key])
            capped = max(Decimal("0.00"), min(variant.stock_qty or Decimal("0.00"), remaining))
            if variant.stock_qty != capped:
                variant.stock_qty = capped
                variant.save(update_fields=["stock_qty"])
            remaining -= capped

        if remaining > 0 and (product.color or product.size):
            color = _norm(product.color)
            size = _norm(product.size)
            variant, _created = ProductVariant.objects.get_or_create(
                product_id=product.pk,
                color=color,
                size=size,
                defaults={"stock_qty": Decimal("0.00")},
            )
            variant.stock_qty = (variant.stock_qty or Decimal("0.00")) + remaining
            variant.save(update_fields=["stock_qty"])
            product_variant_ids[(product.pk, color, size)] = variant.pk

    for line in PurchaseInvoiceLine.objects.all().only("id", "product_id", "color", "size"):
        variant_id = product_variant_ids.get((line.product_id, _norm(line.color), _norm(line.size)))
        if variant_id:
            line.variant_id = variant_id
            line.save(update_fields=["variant"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_color_product_dimensions_product_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('black', 'Black'), ('gray', 'Gray'), ('white', 'White'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('beige', 'Beige'), ('navy', 'Navy'), ('gold', 'Gold'), ('teal', 'Teal')], default='', max_length=16, verbose_name='Color')),
                ('size', models.CharField(blank=True, default='', max_length=120, verbose_name='Size / Spec')),
                ('stock_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Stock Qty')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['product__name', 'color', 'size'],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoice_lines', to='catalog.productvariant', verbose_name='Variant'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.productvariant', verbose_name='Variant'),
        ),
        migrations.RunPython(backfill_product_variants, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'color', 'size'], name='catalog_variant_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'color', 'size'), name='uniq_product_variant_color_size'),
        ),
    ]
