# Generated by Django 6.0.6 on 2026-06-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'permissions': [('issue_invoice', 'Can issue (finalize) invoices'), ('cancel_invoice', 'Can cancel invoices'), ('view_sales_report', 'Can view sales reports')], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
    ]
