# Generated by Django 6.0.6 on 2026-07-05 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlux', '0003_dlux_update_runtime'),
        ('sales', '0002_alter_invoice_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'permissions': [('view_all_customer', 'Can view all customers (not just own)')], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'permissions': [('issue_invoice', 'Can issue (finalize) invoices'), ('cancel_invoice', 'Can cancel invoices'), ('view_sales_report', 'Can view sales reports'), ('view_all_invoice', 'Can view all invoices (not just own)'), ('assign_salesperson', "Can assign an invoice's salesperson")], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_at'], 'permissions': [('view_all_payment', 'Can view all payments (not just own)')], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_as_salesperson', to=settings.AUTH_USER_MODEL, verbose_name='Salesperson'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('recipient', models.CharField(blank=True, max_length=200, verbose_name='Recipient')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Phone')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('out', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12, verbose_name='Status')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Scheduled Date')),
                ('delivered_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Delivered At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='sales.invoice', verbose_name='Invoice')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dlux.scope', verbose_name='Scope')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created_at'],
                'permissions': [('view_all_delivery', 'Can view all deliveries (not just assigned)'), ('assign_delivery', 'Can assign deliveries to couriers')],
                'indexes': [models.Index(fields=['status', '-created_at'], name='sales_deliv_status_idx'), models.Index(fields=['assigned_to', 'status'], name='sales_deliv_assignee_idx')],
            },
        ),
    ]
