# Generated by Django 6.0.6 on 2026-07-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_customer_options_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'permissions': [('issue_invoice', 'Can issue (finalize) invoices'), ('cancel_invoice', 'Can cancel invoices'), ('view_sales_report', 'Can view sales reports'), ('view_all_invoice', 'Can view all invoices (not just own)'), ('assign_salesperson', "Can assign an invoice's salesperson"), ('view_financial_report', 'Can view the financial (fiscal-year) report')], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='attachment',
            field=models.FileField(blank=True, upload_to='invoices/', verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='unit_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True, verbose_name='Unit Cost (USD)'),
        ),
    ]
