# Generated by Django 6.0.6 on 2026-07-11 07:32

import django.db.models.deletion
from django.db import migrations, models


def _norm(value):
    return (value or "").strip()


def backfill_invoice_item_variants(apps, schema_editor):
    InvoiceItem = apps.get_model("sales", "InvoiceItem")
    ProductVariant = apps.get_model("catalog", "ProductVariant")

    variant_lookup = {
        (v.product_id, v.color or "", v.size or ""): v.pk
        for v in ProductVariant.objects.all().only("id", "product_id", "color", "size")
    }
    for item in InvoiceItem.objects.exclude(product_id=None).only("id", "product_id", "color", "size"):
        variant_id = variant_lookup.get((item.product_id, _norm(item.color), _norm(item.size)))
        if variant_id:
            item.variant_id = variant_id
            item.save(update_fields=["variant"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productvariant_purchaseinvoiceline_variant_and_more'),
        ('sales', '0006_invoiceitem_color_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='catalog.productvariant', verbose_name='Variant'),
        ),
        migrations.RunPython(backfill_invoice_item_variants, migrations.RunPython.noop),
    ]
